### ISSUE TITLE
Project Governance Documents

### ISSUE THREAD

**Issue by hythloda** [gittuf/gittuf#128]
Hello gittuf! 

The Linux Foundation has an initial set of documents for you to review that we think are useful for gittuf:

2. [Technical Charter Draft](https://docs.google.com/open?id=1c35OxpKws0jsj0Cf5lyyr-apyhM1bLzOaOS5Yj4YR94)
3. (NOT NEEDED) [Contribution Agreement Draft](https://docs.google.com/open?id=18F6tg3ohyaa1f08W-jijpAwyA1nJevfxJ02g1naD_A8) (NOT NEEDED)
4. (NOT NEEDED)[Series Agreement Draft](https://docs.google.com/open?id=1cEZqAp5-MtUQmNFPWgKidpe5s0uEHtAjZa4r7TbVCCc)(NOT NEEDED)

Please review these materials and let us know if you have any questions. To give you some background on these materials:

## **Technical Project Charter Template**

A technical charter is created for all new projects to define both the project operations and the IP policy.  This document is used to set up an LLC entity, and this becomes the core governance of that LLC.  We have proposed technical oversight for the project falls to a “Technical Steering Committee” made up of the project’s committers. At a later date the TSC is free to evolve how membership on the TSC is determined to accommodate project growth and the evolution of its governance. 

If you like this doc as is let me know and we can adopt it, if you have changes then come to an agreement in together and then we can look at it too. 

## **Project Contribution Agreement**

In order to enable collaboration across organizations, the Linux Foundation and its project hosting entities hold project names, logos and key accounts (e.g., domain names, GitHub accounts, etc.) for the benefit of the project community.  The way we do this is through the execution of the Project Contribution Agreement with the project’s founding organization or, in some cases, individual.  While companies transferring project names and logos to us can continue use those names and logos in accordance with our trademark usage guidelines (please see https://lfprojects.org/policies/trademark-policy/), project names should not be used as part of a commercial product name.  If you are currently using the name of the project as part of a product name, please let us know.

While the Project Contribution Agreement will ask about any trademark registrations, please note your organization may have common law trademark rights in a project name even if a registration has not been filed. Therefore, unless the project name has never been used publicly, we have Project Contribution Agreements signed even if there are no trademark registrations.

## **Series Agreement**

You will note that the Technical Charter refers to the project as being organized as a “series” of LF Projects, LLC. LF Projects, LLC is one of our project hosting entities, and is a Delaware series limited liability company. Using LF Projects, LLC allows us to give a form of legal identity to projects.  The document that gives existence to the project as a series of LF Projects, LLC, is the ‘Series Agreement’. The Series Agreement is a document signed by LF personnel, and no action is required on your part in creation of the series.  We are including a copy of the Series Agreement in this packet because the Technical Charter will include references to the Series Agreement and the Series Manager (an LF employee who can act on behalf of the series). 

## **Next Steps:**

In terms of moving forward, the next steps are as follows:

- [x] Come to agreement on the finalized language for the Technical Charter.  
- [x] We (OpenSSF) are in the process of upgrading and transitioning our GitHub to an Enterprise Account to https://github.com/openssf, so we want to wait on this to avoid duplicate efforts but eventually we can host your project there. In the mean time Add ‘thelinuxfoundation’ as an owner of the GitHub org
- [x] Send .svg of existing logo to [formation@linuxfoundation.org](mailto:formation@linuxfoundation.org)
- [x] We should prepare an announcement concerning the project launching with the OpenSSF jbly@linuxfoundation.org 
- [x] Add the following as a website footer in tandem with an announcement:

>  Copyright © gittuf a Series of LF Projects, LLC
> For web site terms of use, trademark policy and other project policies please see https://lfprojects.org/.

Should you have any questions, please do not hesitate to contact us.  If you’d like to set up time to discuss these documents in further detail, please let us know a few suitable times.

## **Contacts**

Your OpenSSF contact is Amanda Martin @hythloda on GitHub or amartin@linuxfoundation.org with any questions. You can book a time in my [Calendar](https://www.linuxfoundation.org/meetings/amartin56) or invite me to any of your meetings to discuss the documents and I will generally rearrange my calendar to attend.

Project Formation 

If you have any questions about the process of bringing your project to the LF, please reach out to Scott Nicholas, VP of Project Formation, and Todd Benzies, Senior Director of Project Formation, at [formation@linuxfoundation.org](mailto:formation@linuxfoundation.org). 

It's good to review the [FAQ on Project formation](https://docs.google.com/document/d/1TDshar1MIh43s7ehDskh8PbpEhd7eurrpxo7gM9WWco/edit).

Thank you!

**Comment by hythloda** [comment]
We talked with LF legal and @JustinCappos talked with NYU legal and we do not need any signatures!!! Just a vote in the next meeting to approve the charter.

**Comment by adityasaky** [comment]
@hythloda I'm going to move the charter document with the edits to a .md file. I'll open a PR proposing it as the charter on the gittuf/community repo for the TSC to vote / approve.

**Comment by hythloda** [comment]
> @hythloda I'm going to move the charter document with the edits to a .md file. I'll open a PR proposing it as the charter on the gittuf/community repo for the TSC to vote / approve.

This is a great idea! I should do that for future projects. Thanks for working through this with me :)

**Comment by adityasaky** [comment]
No worries, thanks for helping us out on all of this! We're working on the announcement text and so on in parallel.

**Comment by adityasaky** [comment]
https://github.com/gittuf/community/pull/3 has been merged and the charter's been adopted! I'm going to keep this issue open until we resolve action items like the announcement and the website footers.

**Comment by adityasaky** [comment]
The announcement is now live. Thanks @hythloda!

https://openssf.org/blog/2024/01/18/introducing-gittuf-a-security-layer-for-git-repositories/
