### ISSUE TITLE
Settle terminology for RSL entries

### ISSUE THREAD

**Issue by adityasaky** [gittuf/gittuf#130]
The RSL can store two types of objects: an entry and an annotation. Unfortunately, we use the word "entry" in an abstract sense to refer to either of those two types. Some examples:
* the `EntryType` interface
* `GetEntry` which returns the object in the RSL for the specified ID, so this can be either an `Entry` or an `Annotation`
* other APIs

I suggest we use the word "record", possibly as a replacement for the abstract use of the word "entry". I can also see an argument to swap them around, where "entry" is generic and the type that has a ref and target ID becomes a "record". Once this terminology is settled, it should be a fairly easy, if noisy, PR to rename the corresponding APIs. The specification can also be updated at the same time to reflect the change, I foresee a smaller diff there.

**Comment by JustinCappos** [comment]
Keep in mind that record can be a verb as well as a noun.  I read it as a verb the first time I read it in the issue above.

**Comment by adityasaky** [comment]
Maybe "item" for the generic term to refer to either an entry or an annotation?

**Comment by reza-curtmola** [comment]
These are two types of RSL entries. I wonder if we can keep it simple and refer to one as "standard/basic entry" and to the other as "annotation entry"?

**Comment by adityasaky** [comment]
@reza-curtmola I think that's fine too. To summarize, we rename:
* Entry to StandardEntry or RegularEntry, to represent one that records reference state
* EntryType to Entry, making Entry the generic name for any object in the RSL
* APIs that return a StandardEntry to reflect the change

For consistency's sake, I think we could rename Annotation to AnnotationEntry to match StandardEntry (I'm opposed to calling it just Standard in-code).

This suggestion does have the added benefit of not using a generic term "Entry" more specifically, which is the case with using Item as the generic term.
