### ISSUE TITLE
Ensure that git signing is viable

### ISSUE THREAD

**Issue by patzielinski** [gittuf/gittuf#147]
When using gittuf, we should make sure that git signing is viable before we touch anything in the repository - we don't want cases where we've initialized something and it turns out that we can't sign anything.

**Comment by adityasaky** [comment]
Thanks for filing this!

To be very precise, we want to ensure we can sign git commits. gittuf invokes this under the hood for RSL entries and the policy namespace. We ought to file early like we do for when a signing key isn't presented for policy metadata (https://github.com/gittuf/gittuf/blob/main/internal/cmd/policy/persistent/persistent.go#L19). For consistency's sake, I propose making this part of the cmd package, by invoking gitinterface.GetSigningCommand (https://github.com/gittuf/gittuf/blob/main/internal/gitinterface/keys.go#L43) in commands' PreRun / PersistentPreRun.

**Comment by adityasaky** [comment]
Here are some docs on the prerun options we have: https://pkg.go.dev/github.com/spf13/cobra#Command

**Comment by adityasaky** [comment]
Closed by #179
