### ISSUE TITLE
RSL needs a log command 

### ISSUE THREAD

**Issue by neilnaveen** [gittuf/gittuf#274]
### Add a description

RSL needs a log feature, since without it, currently running `gittuf rsl annotate` is impossible, since it requires the commit ID's. This is impossible for the user to fetch, since they cannot view the commit ID's of the RSL entries they want to annotate, since the current log using git is not descriptive enough to really differentiate between RSL entries, and which ones correspond to what state. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by neilnaveen** [comment]
I would like to work on this

**Comment by adityasaky** [comment]
> since it requires the commit ID's.

Is this a wrapper around `git log refs/gittuf/reference-state-log`?

**Comment by adityasaky** [comment]
But, a `gittuf rsl log` sounds like a good idea. It could also do some things like decode the message in the annotation and present it to the user, etc.

**Comment by adityasaky** [comment]
Let's also explore how this is used in conjunction with a pager (like git log) so that we don't fill up a user's scrollback. Apologies for treating this more like Slack than an issue tracker.

**Comment by neilnaveen** [comment]
> > since it requires the commit ID's.
> 
> Is this a wrapper around `git log refs/gittuf/reference-state-log`?

Yes, I thought that this did not give enough information to actually understand what entry was what , I was also thinking about adding a condensed version of `list-rules` for each entry, so a basic picture of what the policy state was at that entry.

**Comment by neilnaveen** [comment]
Fixed in PR #282

**Comment by adityasaky** [comment]
Closed by #282.
