### ISSUE TITLE
Does gittuf git ref rules go into packed refs?

### ISSUE THREAD

**Issue by neilnaveen** [gittuf/gittuf#290]
### Add a description

Does gittuf git ref rules go into packed refs? For example lets say I have a rule that affects refs/tags/v1, if my refs are packed and stored in the packed-refs file, is gittuf able to verify with this?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adityasaky** [comment]
Good question. We don't inspect `refs/` directly, so this is a question of whether go-git does. I haven't looked this up but it's definitely something we should check in their implementation / compatibility guide. Data points such as this will help influence #2 and #286 etc. cc @patzielinski

**Comment by adityasaky** [comment]
Great! I'm going to close this, then. Thanks for checking, @patzielinski.
