### ISSUE TITLE
Tag verification functionality 

### ISSUE THREAD

**Issue by neilnaveen** [gittuf/gittuf#292]
### Add a description

Currently, revoking edit permissions for keys on a tag ref causes gittuf verify-tag to fail for that tag.

If in a git repository there was a rule protect-v1 which only allowed users user1 and user2 to edit the ref refs/tags/v1. Then if user1 then creates tag v1, this will pass tag verification. However, removing user1 from the rule, and recording it in the RSL later makes gittuf verify-tag v1 fail. This happens because tag verification checks the latest RSL entry for tag refs, which would indicate user1 shouldn't have created v1 according to the most recent rules. Unlike commits, where verification is based on their specific RSL entries, tags don't have this flexibility. 

How would it be possible to allow tag verification have the same flexibility as commit verification, each one referencing its own RSL entry, based on when it was created?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adityasaky** [comment]
I'm not able to reproduce this, can you please add the commands you ran?

Here's what I did:

0. gittuf trust init etc.
1. gittuf policy add-rule with two keys, protecting refs/tags/v1
2. git tag, signed with one of the keys (I set git config --local to use one of the two test keys)
3. gittuf rsl record refs/tags/v1
4. gittuf policy add-rule (same rule name, removed the key I used to sign the tag / RSL entry for tag)
5. gittuf verify-tag v1

This returns:
```
v1: good signature for RSL entry and tag
```

**Comment by neilnaveen** [comment]
After you revoked the key, did you record the new state in the RSL?

**Comment by neilnaveen** [comment]
Looking at your steps, the only different command that I performed was that before I created the rules, I record the state into the RSL.

**Comment by adityasaky** [comment]
> record the new state

the new state of what, sorry?

**Comment by neilnaveen** [comment]
I rebuilt my gittuf, I had built a dirty version of it, and with the regular code everything is working fine

**Comment by adityasaky** [comment]
Thanks!
