### ISSUE TITLE
Wildcard in rule pattern doesn't apply to subdirectories

### ISSUE THREAD

**Issue by adityasaky** [gittuf/gittuf#309]
### What happened?

gittuf currently uses glob-style patterns. This means that `file:foo/*` will apply to all files in the foo/ directory but not in the foo/bar/ directory. The glob-style patterns are based off the upstream TUF specification but they're not ideal for gittuf. Instead, I propose we switch our patterns to align with [gitignore](https://git-scm.com/docs/gitignore#_pattern_format). This should be a drop-in replacement. Note that with this change, `file:foo/*` will still not match other `/`, but we can at least support `file:foo/**`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adityasaky** [comment]
Thinking aloud, but I think what we really want is just fnmatch? No need of ** then, fnmatch doesn't special case directory separaters. It operates strictly on strings as well.

**Comment by JustinCappos** [comment]
So what would the behavior be in this case then?

**Comment by JustinCappos** [comment]
What if you don't want to match subdirectories?  Is that use case important?

**Comment by adityasaky** [comment]
Do you mean where `foo` has three subdirectories `a`, `b`, `c` and you want a pattern to only apply to `a` and `b` and not `c`? fnmatch doesn't make this trivial (regex may be a better option here but I don't know if we want the complexity of regex). I want to note though that you could support this by explicitly defining a terminating rule for `foo/c` and then include a `foo/*`. Either way, you're explicitly declaring the subdirectory you do not want to match.
