### ISSUE TITLE
`verify-commit` and `verify-tag` always exit 0

### ISSUE THREAD

**Issue by flandweber** [gittuf/gittuf#382]
As a user I'd expect any verification command to exit with a non-zero exit status if the verification fails.
Especially relevant for scripting.

verify-ref behaves that way, but verify-commit and verify-tag don't:

```
$ gittuf verify-commit 64ff87bd606fc4ae5ed973f113830ca35ef2b0e4
64ff87bd606fc4ae5ed973f113830ca35ef2b0e4: no signature found

$ echo $?
0
```

@adityasaky Feel free to close if this is no longer relevant due to the possible removal of the mentioned commands!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adityasaky** [comment]
The reason this return non zero ever is because you can verify multiple commit signatures. It's possible we should have set the ret to non zero if even one of those commits failed sig verification for whatever reason.

**Comment by adityasaky** [comment]
Closing this as we've dropped these cmds.
