### ISSUE TITLE
gittuf User Experience

### ISSUE THREAD

**Issue by adityasaky** [gittuf/gittuf#4]
The gittuf CLI provides "low level" commands but we need to build in some "high level" workflows for users to use 99% of the time. This issue is to discuss what these workflows look like and their UX.

**Comment by errordeveloper** [comment]
I would imagine that it should be possible to leverage `.git/hooks`, but these are up to the user to create and manage. What would be interesting is whether it's possible to have a gittuf policy that enforces hooks, which would mean having a policy on something that is not in git tree. If gittuf can enforce hooks, that alone creates an interesting value proposition.

Another discussion point would be to have a git plugin, of course.
Having a way to map key IDs to e.g. GitHub usernames would seem like another usability enhancement. I can imagine this might be seen as a security compromise, but perhaps there is a way to deliver this functionality in a sensible way.

One low hanging fruit seems to be `gittuf policy {list-rules,show-rule}`. As a newbe I was surprised that there isn't a way to see what policies exist.

**Comment by adityasaky** [comment]
> What would be interesting is whether it's possible to have a gittuf policy that enforces hooks, which would mean having a policy on something that is not in git tree. If gittuf can enforce hooks, that alone creates an interesting value proposition.

That's certainly an interesting idea, I'm going to think about it to see what that'd look like. @JustinCappos is already on this thread, this might be interesting to @patzielinski as well.

>  Having a way to map key IDs to e.g. GitHub usernames would seem like another usability enhancement. I can imagine this might be seen as a security compromise, but perhaps there is a way to deliver this functionality in a sensible way.

What do you have in mind here? The simplest way may be to ensure that at "username registration" time in the gittuf policy, the claimed github username exposes the same key (eg: https://github.com/adityasaky.gpg). But we'd have to work out how this is continually validated, say when a user updates the keys on github but not in gittuf.

> One low-hanging fruit seems to be gittuf policy {list-rules,show-rule}. As a newbie, I was surprised that there isn't a way to see what policies are already defined.

Opened #191 to track this separately!

**Comment by adityasaky** [comment]
Closing this, as we've seen issues discussing more specific UX concerns.
