### ISSUE TITLE
Add  `ssh.NewSignerFromFile`

### ISSUE THREAD

**Issue by lukpueh** [gittuf/gittuf#446]
A `ssh.NewSignerFromFile` for these 10 lines might be helpful.

_Originally posted by @lukpueh in https://github.com/gittuf/gittuf/pull/436#discussion_r1642333164_

**Comment by lukpueh** [comment]
Just saw that #436 already includes a NewSignerFromFile.

**Comment by adityasaky** [comment]
I dropped this from #436.
