### ISSUE TITLE
Attestations namespace initialization prevents running `gittuf trust init` again in case of failure

### ISSUE THREAD

**Issue by patzielinski** [gittuf/gittuf#453]
### What happened?

When initializing gittuf with `gittuf trust init`, the attestations namespace is initialized with an unsigned commit. If the trust initialization process fails for some reason after this point, the attestations ref will have a non-zero hash due to the commit, causing the zero hash check below to fail. At this point, `gittuf trust init` will keep failing on this check.

This can be worked around by deleting the `.git` folder and trying again, but opening this in case we want to change how this is done.

```go
// internal/attestations/attestations.go

// InitializeNamespace creates a namespace to store attestations for
// verification with gittuf. The ref is created with an initial, unsigned commit
// that is unsigned.
func InitializeNamespace(repo *git.Repository) error {
	if ref, err := repo.Reference(plumbing.ReferenceName(Ref), true); err != nil {
		if !errors.Is(err, plumbing.ErrReferenceNotFound) {
			return err
		}
	} else if !ref.Hash().IsZero() { // The hash is not zero due to line [1] below being run, even if there was an issue later
		return ErrAttestationsExist
	}

	treeHash, err := gitinterface.WriteTree(repo, nil)
	if err != nil {
		return err
	}

	_, err = gitinterface.Commit(repo, treeHash, Ref, initialCommitMessage, false) // [1]
	return err
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adityasaky** [comment]
> This can be worked around by deleting the .git folder and trying again, but opening this in case we want to change how this is done.

No, this assumes gittuf is being initialized in a fresh repository. Let's update attestations to behave like the other namespaces, but can you check if that happens naturally with #372?
