### ISSUE TITLE
Request for Reviewer Status

### ISSUE THREAD

**Issue by neilnaveen** [gittuf/gittuf#459]
### Add a description

I would like to request the status of a reviewer, and since gittuf does not have a defined contribution ladder, I am referencing the [Kubernetes community membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md) to illustrate my qualifications and contributions. Based on these guidelines, I think I fit the role of a Reviewer.

I have consistently contributed to gittuf from November 1, 2023. Below is a summary of my significant contributions and ongoing work.

## Critical Features 

- Display Package:
    - Developed gittuf policy listrules to view the current policy state.
    - Implemented gittuf rsl log to be used with attestations, enabling approvers to understand RSL entries and their implications.
- Root Key Management:
    - Added functionality to add and remove root keys from the root of trust.
    - Enabled checks to ensure the root keys used to bootstrap the project are the expected bootstrapping root keys in gittuf clone.
- Policy-Staging Ref:
    - Created the policy-staging ref, allowing gittuf to be used with a threshold higher than 1, enabling multi-reviewer policy approval.
    - Currently advancing the policy-staging area to support multiple "staging areas," each mergeable into the main policy ref.

### PRs Opened
1. https://github.com/gittuf/gittuf/pull/162, 
1. https://github.com/gittuf/gittuf/pull/166, 
1. https://github.com/gittuf/gittuf/pull/172, 
1. https://github.com/gittuf/gittuf/pull/173, 
1. https://github.com/gittuf/gittuf/pull/189, 
1. https://github.com/gittuf/gittuf/pull/198, 
1. https://github.com/gittuf/gittuf/pull/209, 
1. https://github.com/gittuf/gittuf/pull/213, 
1. https://github.com/gittuf/gittuf/pull/221, 
1. https://github.com/gittuf/gittuf/pull/225, 
1. https://github.com/gittuf/gittuf/pull/251, 
1. https://github.com/gittuf/gittuf/pull/252, 
1. https://github.com/gittuf/gittuf/pull/260, 
1. https://github.com/gittuf/gittuf/pull/282, 
1. https://github.com/gittuf/gittuf/pull/307, 
1. https://github.com/gittuf/gittuf/pull/312, 
1. https://github.com/gittuf/gittuf/pull/320, 
1. https://github.com/gittuf/gittuf/pull/329, 
1. https://github.com/gittuf/gittuf/pull/337, 
1. https://github.com/gittuf/gittuf/pull/344, 
1. https://github.com/gittuf/gittuf/pull/358, 
1. https://github.com/gittuf/gittuf/pull/361, 
1. https://github.com/gittuf/gittuf/pull/369, 
1. https://github.com/gittuf/gittuf/pull/381, 
1. https://github.com/gittuf/gittuf/pull/393

### PRs Reviewed
1. https://github.com/gittuf/gittuf/pull/261, 
1. https://github.com/gittuf/gittuf/pull/313, 
1. https://github.com/gittuf/gittuf/pull/341, 
1. https://github.com/gittuf/gittuf/pull/367, 
1. https://github.com/gittuf/gittuf/pull/372, 
1. https://github.com/gittuf/gittuf/pull/383, 
1. https://github.com/gittuf/gittuf/pull/392, 
1. https://github.com/gittuf/gittuf/pull/408, 
1. https://github.com/gittuf/gittuf/pull/419,
1. https://github.com/gittuf/gittuf/pull/456

### Issues Opened
1. https://github.com/gittuf/gittuf/issues/274, 
1. https://github.com/gittuf/gittuf/issues/290, 
1. https://github.com/gittuf/gittuf/issues/328, 
1. https://github.com/gittuf/gittuf/issues/345, 
1. https://github.com/gittuf/gittuf/issues/368, 
1. https://github.com/gittuf/gittuf/issues/371

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by neilnaveen** [comment]
cc @adityasaky @wlynch @JustinCappos @patzielinski @reza-curtmola

**Comment by adityasaky** [comment]
I think you've made some incredible contributions to the project, and you've caught things maintainers have missed. Having you on board as a reviewer would be great! With you and @patzielinski joining as reviewers, we can also bump up the required approvals to 2.

**Comment by wlynch** [comment]
👍 LGTM.

**Comment by neilnaveen** [comment]
I have opened a PR https://github.com/gittuf/gittuf/pull/460

**Comment by adityasaky** [comment]
Closed by #460
