### ISSUE TITLE
gittuf Transport

### ISSUE THREAD

**Issue by patzielinski** [gittuf/gittuf#465]
The transport introduced in #411 is an alternative to the default transport provided by Git, and performs some gittuf operations transparently to the end-user.

It's in an alpha state at the moment and one needs to explicitly opt-in to using it (i.e. it is not used by default, even when running `make`)

This issue is to track the status / improvements to the transport.

**Comment by adityasaky** [comment]
I'm going to close this, I think overall it's better to have separate issues like #505 #491 etc.
