### ISSUE TITLE
Enable logging

### ISSUE THREAD

**Issue by adityasaky** [gittuf/gittuf#54]
gittuf's implementations should include verbose logging for the benefit of users. Actions within the `internal/repository` package in particular should log at various checkpoints what's happening. Further, the user should be able to see these logs via a `--verbose` flag they can invoke from the CLI.

**Comment by adityasaky** [comment]
Relevant: https://pkg.go.dev/log/slog

**Comment by adityasaky** [comment]
I think slog is overkill for gittuf's workflow. But otherwise, I agree with what you're proposing. Go for it!

**Comment by spectre10** [comment]
> I think slog is overkill for gittuf's workflow.

yeah, I though so too. I just made it with the `log` package. Let me know your thoughts. (#180 )

**Comment by naveensrinivasan** [comment]
> I think slog is overkill for gittuf's workflow. But otherwise, I agree with what you're proposing. Go for it!

Why do think so? I would recommend using slog with an interface so that it provides an ideal option to be able to swap.

**Comment by adityasaky** [comment]
When I was first considering what we wanted, I was thinking of it very much in the context of messages presented to users. I expected the log data's  consumers to be exclusively users passing in `--verbose`. Thinking about it some more, it's probably a good idea after all to start off with something structured which is then presented to the user as regular text. The JSON formatted logs might be useful elsewhere such as in a [CI context](https://github.com/gittuf/ci-demo) or any other "hosted" gittuf verification context. Thanks for your input @naveensrinivasan!

**Comment by naveensrinivasan** [comment]
> When I was first considering what we wanted, I was thinking of it very much in the context of messages presented to users. I expected the log data's consumers to be exclusively users passing in `--verbose`. Thinking about it some more, it's probably a good idea after all to start off with something structured which is then presented to the user as regular text. The JSON formatted logs might be useful elsewhere such as in a [CI context](https://github.com/gittuf/ci-demo) or any other "hosted" gittuf verification context. Thanks for your input @naveensrinivasan!

Thanks for the update 👍

**Comment by Dev-Voldemort** [comment]
Hey, I would like to work on adding log statements as I am currently exploring the code-base. Can I DM you on slack for specific queries? @adityasaky

**Comment by adityasaky** [comment]
Sure! Feel free to use the #gittuf channel too.

**Comment by adityasaky** [comment]
Closed by https://github.com/gittuf/gittuf/pull/302.
